"""
gen_oui_data.py
---------------
Converts the IEEE Registration Authority public OUI registries into the
OuiData.cpp source consumed by VendorResolver. IEEE publishes three files
covering the three allocation block widths:

    https://standards-oui.ieee.org/oui/oui.csv      (MA-L  /24, 6 hex chars)
    https://standards-oui.ieee.org/oui28/mam.csv    (MA-M  /28, 7 hex chars)
    https://standards-oui.ieee.org/oui36/oui36.csv  (MA-S  /36, 9 hex chars)

These are public assignment records — IEEE provides them for free public use
with no attribution requirement and no copyright restriction. Bundling them
into a closed-source binary is therefore unambiguous, unlike Wireshark's GPL
manuf compilation or Nmap's GPL nmap-mac-prefixes.

Output format: one "HEXPREFIX VENDOR\\n" line per entry, packed into ~8 KB
raw-string chunks to stay under MSVC's 16380-char single-literal cap.
VendorResolver does longest-prefix-first lookup (9 -> 7 -> 6 hex chars), so
MA-S/MA-M assignments win over the legacy MA-L 24-bit blanket entries.

Usage:
    python tools/gen_oui_data.py <input-dir> <output-OuiData.cpp>

The input directory is expected to contain oui.csv (required), mam.csv
(optional) and oui36.csv (optional).
"""

import csv
import os
import sys


_HEX = set("0123456789ABCDEF")


def _read_ieee_csv(path, seen, entries):
    kept = 0
    skipped = 0
    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.reader(f)
        header = next(reader, None)
        if not header or len(header) < 3:
            return (0, 0)
        for row in reader:
            if len(row) < 3:
                skipped += 1
                continue
            assignment = row[1].strip().upper()
            vendor = row[2].strip().replace("\r", " ").replace("\n", " ")
            if not assignment or not vendor:
                skipped += 1
                continue
            if any(c not in _HEX for c in assignment):
                skipped += 1
                continue
            if len(assignment) not in (6, 7, 9):
                skipped += 1
                continue
            if assignment in seen:
                skipped += 1
                continue
            seen.add(assignment)
            entries.append((assignment, vendor))
            kept += 1
    return (kept, skipped)


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_oui_data.py <input-dir> <output-OuiData.cpp>\n")
        return 1

    src_dir = sys.argv[1]
    dst_path = sys.argv[2]

    inputs = [
        ("oui.csv",   True),
        ("mam.csv",   False),
        ("oui36.csv", False),
    ]

    entries = []
    seen = set()
    total_kept = 0
    total_skipped = 0

    for fname, required in inputs:
        path = os.path.join(src_dir, fname)
        if not os.path.exists(path):
            if required:
                sys.stderr.write("FATAL: required input " + path + " not found\n")
                return 2
            sys.stderr.write("note: " + fname + " not present; skipping\n")
            continue
        k, s = _read_ieee_csv(path, seen, entries)
        total_kept += k
        total_skipped += s
        sys.stderr.write("  " + fname + ": kept " + str(k) + ", skipped " + str(s) + "\n")

    cleaned_lines = [a + " " + v for a, v in entries]
    cleaned = "\n".join(cleaned_lines) + "\n"

    target = 8000
    chunks = []
    buf = []
    buf_len = 0
    for line in cleaned_lines:
        s = line + "\n"
        if buf_len + len(s) > target and buf:
            chunks.append("".join(buf))
            buf = [s]
            buf_len = len(s)
        else:
            buf.append(s)
            buf_len += len(s)
    if buf:
        chunks.append("".join(buf))

    delim = "OUI"
    bad = []
    for i, c in enumerate(chunks):
        if ")" + delim + '"' in c:
            bad.append(i)
    if bad:
        sys.stderr.write("FATAL: delimiter conflict in chunks: " + str(bad) + "\n")
        return 3

    out = []
    out.append("// =============================================================================")
    out.append("// OuiData.cpp - Auto-generated from the IEEE Registration Authority")
    out.append("//   Sources: https://standards-oui.ieee.org/oui/oui.csv")
    out.append("//            https://standards-oui.ieee.org/oui28/mam.csv")
    out.append("//            https://standards-oui.ieee.org/oui36/oui36.csv")
    out.append("//   Public IEEE assignment records - free public use, no copyright claim,")
    out.append("//   no attribution requirement. Covers MA-L (/24), MA-M (/28) and MA-S (/36).")
    out.append("//   Do NOT edit this file by hand. Re-run tools/gen_oui_data.py to refresh.")
    out.append("// =============================================================================")
    out.append("")
    out.append('#include "OuiData.h"')
    out.append("")
    out.append("namespace netlens {")
    out.append("")
    out.append("// " + str(total_kept) + " OUI entries (" + str(total_skipped) +
               " skipped), " + str(len(cleaned)) + " bytes after cleanup.")
    out.append("const char* const kOuiBlob =")
    for c in chunks:
        out.append("R\"" + delim + "(" + c + ")" + delim + "\"")
    out.append(";")
    out.append("")
    out.append("const std::size_t kOuiBlobSize = " + str(len(cleaned)) + ";")
    out.append("")
    out.append("} // namespace netlens")

    with open(dst_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    size_kb = os.path.getsize(dst_path) / 1024.0
    sys.stderr.write(
        "\nwrote " + dst_path + " (" + ("%.1f" % size_kb) + " KB, " +
        str(total_kept) + " OUI entries, " + str(total_skipped) + " skipped, " +
        str(len(chunks)) + " chunks)\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
